#Build multi-stage del frontend

#Immagine Compilazione
FROM node:20-alpine AS builder
WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/. .
RUN npm run build

#Immagine da servire
FROM alpine:latest
WORKDIR /usr/share/app/frontendù

#Prendo i file statici
COPY --from=builder /app/dist .